#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ElementType {
	Master,
	Uinteger,
	Integer,
	Float,
	String,
	Utf8,
	Binary,
	Date,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ElementInfo {
	pub id: u32,
	pub name: &'static str,
	pub typ: ElementType,
	pub mandatory: bool,
	pub multiple: bool,
}

pub struct Elements;

impl Elements {
	pub fn info(id: u32) -> Option<ElementInfo> {
		ELEMENT_DATABASE.iter().find(|e| e.id == id).copied()
	}

	pub fn is_master(id: u32) -> bool {
		Self::info(id).map(|e| e.typ == ElementType::Master).unwrap_or(false)
	}

	pub fn name(id: u32) -> &'static str {
		Self::info(id).map(|e| e.name).unwrap_or("Unknown")
	}
}

const ELEMENT_DATABASE: &[ElementInfo] = &[
	// EBML Header
	ElementInfo {
		id: 0x1A45DFA3,
		name: "EBML",
		typ: ElementType::Master,
		mandatory: true,
		multiple: false,
	},
	ElementInfo {
		id: 0x4286,
		name: "EBMLVersion",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x42F7,
		name: "EBMLReadVersion",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x42F2,
		name: "EBMLMaxIDLength",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x42F3,
		name: "EBMLMaxSizeLength",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x4282,
		name: "DocType",
		typ: ElementType::String,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x4287,
		name: "DocTypeVersion",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x42F1,
		name: "DocTypeReadVersion",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	// Segment
	ElementInfo {
		id: 0x18538067,
		name: "Segment",
		typ: ElementType::Master,
		mandatory: true,
		multiple: false,
	},
	// SeekHead
	ElementInfo {
		id: 0x114D9B74,
		name: "SeekHead",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x4DBB,
		name: "Seek",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x53AB,
		name: "SeekID",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x53AC,
		name: "SeekPosition",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	// Info
	ElementInfo {
		id: 0x1549A966,
		name: "Info",
		typ: ElementType::Master,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x73A4,
		name: "SegmentUID",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x73C0,
		name: "SegmentFilename",
		typ: ElementType::Utf8,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x3CB923,
		name: "PrevUID",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x3C83AB,
		name: "PrevFilename",
		typ: ElementType::Utf8,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x3EB923,
		name: "NextUID",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x3E83BB,
		name: "NextFilename",
		typ: ElementType::Utf8,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x2AD7B1,
		name: "TimecodeScale",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x4489,
		name: "Duration",
		typ: ElementType::Float,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x4461,
		name: "DateUTC",
		typ: ElementType::Date,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x7BA9,
		name: "Title",
		typ: ElementType::Utf8,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x4D80,
		name: "MuxingApp",
		typ: ElementType::Utf8,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x5741,
		name: "WritingApp",
		typ: ElementType::Utf8,
		mandatory: false,
		multiple: false,
	},
	// Tracks
	ElementInfo {
		id: 0x1654AE6B,
		name: "Tracks",
		typ: ElementType::Master,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xAE,
		name: "TrackEntry",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0xD7,
		name: "TrackNumber",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x73C5,
		name: "TrackUID",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x83,
		name: "TrackType",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x88,
		name: "FlagEnabled",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x85,
		name: "FlagDefault",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x9C,
		name: "FlagForced",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x9F,
		name: "FlagLacing",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x55,
		name: "TrackOffset",
		typ: ElementType::Integer,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x537F,
		name: "TrackMinCache",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x6DE7,
		name: "TrackMaxCache",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x23E383,
		name: "DefaultDuration",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x234E7A,
		name: "DefaultDecodedFieldDuration",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x23314F,
		name: "TrackTimecodeScale",
		typ: ElementType::Float,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x137F,
		name: "TrackName",
		typ: ElementType::Utf8,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x22B59C,
		name: "TrackLanguage",
		typ: ElementType::String,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x86,
		name: "CodecID",
		typ: ElementType::String,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x258688,
		name: "CodecName",
		typ: ElementType::Utf8,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x3A9697,
		name: "CodecSettings",
		typ: ElementType::String,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x3B4040,
		name: "CodecInfoURL",
		typ: ElementType::String,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x26B240,
		name: "CodecDownloadURL",
		typ: ElementType::String,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0xAA,
		name: "CodecDecodeAll",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x6C,
		name: "TrackOverlay",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x56AA,
		name: "CodecDelay",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x56BB,
		name: "SeekPreRoll",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	// Video Settings
	ElementInfo {
		id: 0xE0,
		name: "Video",
		typ: ElementType::Master,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x9A,
		name: "FlagInterlaced",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x9D,
		name: "FieldOrder",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x9E,
		name: "StereoMode",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x53B8,
		name: "AlphaMode",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x53C0,
		name: "OldStereoMode",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xB0,
		name: "PixelWidth",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xBA,
		name: "PixelHeight",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x54AA,
		name: "PixelCropBottom",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x54BB,
		name: "PixelCropTop",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x54CC,
		name: "PixelCropLeft",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x54DD,
		name: "PixelCropRight",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x54B0,
		name: "DisplayWidth",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x54BA,
		name: "DisplayHeight",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x54B2,
		name: "DisplayUnit",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x54B3,
		name: "AspectRatioType",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x2EB524,
		name: "ColorSpace",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x2FB523,
		name: "GammaValue",
		typ: ElementType::Float,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x2383E3,
		name: "FrameRate",
		typ: ElementType::Float,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x55B0,
		name: "MatrixCoefficients",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x55B1,
		name: "BitsPerChannel",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x55B2,
		name: "ChromaSubsamplingHorz",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x55B3,
		name: "ChromaSubsamplingVert",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x55B4,
		name: "CbSubsamplingHorz",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x55B5,
		name: "CbSubsamplingVert",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x55B6,
		name: "ChromaSitingHorz",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x55B7,
		name: "ChromaSitingVert",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x55B8,
		name: "Range",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x55B9,
		name: "TransferCharacteristics",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x55BA,
		name: "Primaries",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x55BB,
		name: "MaxCLL",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x55BC,
		name: "MaxFALL",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x55D0,
		name: "MasterMetadata",
		typ: ElementType::Master,
		mandatory: false,
		multiple: false,
	},
	// Audio Settings
	ElementInfo {
		id: 0xE1,
		name: "Audio",
		typ: ElementType::Master,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xB5,
		name: "SamplingFrequency",
		typ: ElementType::Float,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x78B5,
		name: "OutputSamplingFrequency",
		typ: ElementType::Float,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x9F,
		name: "Channels",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x7D7B,
		name: "ChannelPositions",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x6264,
		name: "BitDepth",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	// Subtitles
	ElementInfo {
		id: 0xE2,
		name: "SubtitleTrack",
		typ: ElementType::Master,
		mandatory: false,
		multiple: false,
	},
	// Cluster
	ElementInfo {
		id: 0x1F43B675,
		name: "Cluster",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0xE7,
		name: "Timecode",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x5854,
		name: "SilentTracks",
		typ: ElementType::Master,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x58D7,
		name: "SilentTrackNumber",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0xA7,
		name: "Position",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xAB,
		name: "PrevSize",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	// BlockGroup
	ElementInfo {
		id: 0xA0,
		name: "BlockGroup",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0xA1,
		name: "Block",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xA2,
		name: "BlockVirtual",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x75A1,
		name: "BlockAdditions",
		typ: ElementType::Master,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xA6,
		name: "BlockMore",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0xEE,
		name: "BlockAddID",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xA5,
		name: "BlockAdditional",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x9B,
		name: "BlockDuration",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xCA,
		name: "ReferencePriority",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xFB,
		name: "ReferenceBlock",
		typ: ElementType::Integer,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0xFD,
		name: "ReferenceVirtual",
		typ: ElementType::Integer,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xA4,
		name: "CodecState",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x75A2,
		name: "DiscardPadding",
		typ: ElementType::Integer,
		mandatory: false,
		multiple: false,
	},
	// SimpleBlock
	ElementInfo {
		id: 0xA3,
		name: "SimpleBlock",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: true,
	},
	// Cues
	ElementInfo {
		id: 0x1C53BB6B,
		name: "Cues",
		typ: ElementType::Master,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xBB,
		name: "CuePoint",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0xB3,
		name: "CueTime",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xB7,
		name: "CueTrackPositions",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0xF7,
		name: "CueTrack",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xF1,
		name: "CueClusterPosition",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x5378,
		name: "CueRelativePosition",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xB2,
		name: "CueDuration",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xEA,
		name: "CueBlockNumber",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x5387,
		name: "CueCodecState",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x5381,
		name: "CueReference",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x5388,
		name: "CueRefTime",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xEB,
		name: "CueRefCluster",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x535F,
		name: "CueRefNumber",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x6532,
		name: "CueRefCodecState",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	// Attachments
	ElementInfo {
		id: 0x1941A469,
		name: "Attachments",
		typ: ElementType::Master,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x61A7,
		name: "AttachedFile",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x467E,
		name: "FileDescription",
		typ: ElementType::Utf8,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x466E,
		name: "FileName",
		typ: ElementType::Utf8,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x4660,
		name: "FileMimeType",
		typ: ElementType::String,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x465C,
		name: "FileData",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x46AE,
		name: "FileUID",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x4675,
		name: "FileReferral",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x4740,
		name: "FileUsedStartTime",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x4741,
		name: "FileUsedEndTime",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	// Chapters
	ElementInfo {
		id: 0x1043A770,
		name: "Chapters",
		typ: ElementType::Master,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x45B9,
		name: "EditionEntry",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x45BC,
		name: "EditionUID",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x45BD,
		name: "EditionFlagHidden",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x45DB,
		name: "EditionFlagDefault",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x45DD,
		name: "EditionFlagOrdered",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0xB6,
		name: "ChapterAtom",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x73C4,
		name: "ChapterUID",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x91,
		name: "ChapterTimeStart",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x92,
		name: "ChapterTimeEnd",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x98,
		name: "ChapterFlagHidden",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x4598,
		name: "ChapterFlagEnabled",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x6944,
		name: "ChapterSegmentUID",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x6955,
		name: "ChapterSegmentEditionUID",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x67C4,
		name: "ChapterPhysicalEquiv",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x80,
		name: "ChapterTrack",
		typ: ElementType::Master,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x89,
		name: "ChapterTrackNumber",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x85,
		name: "ChapterDisplay",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x437C,
		name: "ChapString",
		typ: ElementType::Utf8,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x437E,
		name: "ChapLanguage",
		typ: ElementType::String,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x4782,
		name: "ChapLanguageIETF",
		typ: ElementType::String,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x437D,
		name: "ChapCountry",
		typ: ElementType::String,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x6C,
		name: "ChapterProcess",
		typ: ElementType::Master,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x6955,
		name: "ChapterProcessCodecID",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x450D,
		name: "ChapterProcessPrivate",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x6911,
		name: "ChapterProcessCommand",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x6922,
		name: "ChapterProcessTime",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x6933,
		name: "ChapterProcessData",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: false,
	},
	// Tags
	ElementInfo {
		id: 0x1254C367,
		name: "Tags",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x7373,
		name: "Tag",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x63C0,
		name: "Targets",
		typ: ElementType::Master,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x68CA,
		name: "TargetTypeValue",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x63CA,
		name: "TargetType",
		typ: ElementType::String,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x63C5,
		name: "TagTrackUID",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x63C9,
		name: "TagEditionUID",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x63C4,
		name: "TagChapterUID",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x63C6,
		name: "TagAttachmentUID",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x67C8,
		name: "SimpleTag",
		typ: ElementType::Master,
		mandatory: false,
		multiple: true,
	},
	ElementInfo {
		id: 0x45A3,
		name: "TagName",
		typ: ElementType::Utf8,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x4487,
		name: "TagLanguage",
		typ: ElementType::String,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x4484,
		name: "TagLanguageIETF",
		typ: ElementType::String,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x4485,
		name: "TagDefault",
		typ: ElementType::Uinteger,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x4487,
		name: "TagString",
		typ: ElementType::Utf8,
		mandatory: false,
		multiple: false,
	},
	ElementInfo {
		id: 0x4488,
		name: "TagBinary",
		typ: ElementType::Binary,
		mandatory: false,
		multiple: false,
	},
];
